[[redirects]]
from = "https://domfyi.netlify.com/*"
to = "https://dom.fyi/:splat"
status = 301
force = true
[[redirects]]
from = "https://yearday.org"
to = "https://dom.fyi/2019.220"
status = 200
force = true